### ISSUE TITLE
Improve error handling of update-format-crau

### ISSUE THREAD

**Issue by dongsupark** [flatcar/ue-rs#28]
- [x] Currently `parse_signature_data` and `verify_sig_pubkey` return `Option` instead of `Result`. That was written for simplicity. But we are seeing more cases where clearer error handling with Result is needed.
/cc @wrl 
   - https://github.com/flatcar/ue-rs/pull/30

- [ ] the dummy signature error is printed too prominently, we skip over it but it looks like the program crashed if you don't pay attention to the last line
```
Parsed and verified signature data from file "/var/tmp/outdir/.unverified/oem-ami.gz"
```
which indicates that it was successful.
(suggested by @pothos)

**Comment by pothos** [comment]
The comment is here: https://github.com/flatcar/ue-rs/pull/23#discussion_r1385292700

**Comment by dongsupark** [comment]
The 1st issue was done by https://github.com/flatcar/ue-rs/pull/30

**Comment by pothos** [comment]
The anyhow PR removed the printing of the signature error, we can close this.
