### ISSUE TITLE
wire up omaha::Hash<T> with DynDigest

### ISSUE THREAD

**Issue by dongsupark** [flatcar/ue-rs#31]
Currently `hash_on_disk` only supports only `Sha256`, it simply relies on Sha256, although `omaha::Hash` has both Sha256 and Sha1.

For potential supports of `Sha1`, it might be interesting to look into `digest::DynDigest` of Rustcrypto that supports multiple hash functions at the same with generics.

**Comment by pothos** [comment]
It would be good to support sha1 hashes in the Omaha response and check them if available. With an old Nebraska version one only get sha1 when syncing from the public Nebraska.

**Comment by pothos** [comment]
PR in https://github.com/flatcar/ue-rs/pull/47
